from setting import directory as dr
from spreadsheet import spreadsheet

tableau_dir = dr.dropbox_dir + '/광고사업부/데이터컨설팅/Tableau'
asset_dir = tableau_dir + '/asset'
raw_dir = dr.download_dir
result_dir =  dr.download_dir

doc = spreadsheet.spread_document_read('https://docs.google.com/spreadsheets/d/1w23AdEYLf4OJDlTElf2vwbVPttctSx-2nB51ZHQDEJQ/edit#gid=0')
owner_sheet = spreadsheet.spread_sheet(doc, 'Owner 정보')
account_sheet = spreadsheet.spread_sheet(doc, '광고주 정보')

google_dict = {
    'advertising_channel_sub_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'SEARCH_MOBILE_APP',
         3 : 'DISPLAY_MOBILE_APP',
         4 : 'SEARCH_EXPRESS',
         5 : 'DISPLAY_EXPRESS',
         6 : 'SHOPPING_SMART_ADS',
         7 : 'DISPLAY_GMAIL_AD',
         8 : 'DISPLAY_SMART_CAMPAIGN',
         9 : 'VIDEO_OUTSTREAM',
         10 : 'VIDEO_ACTION',
         11 : 'VIDEO_NON_SKIPPABLE',
         12 : 'APP_CAMPAIGN',
         13 : 'APP_CAMPAIGN_FOR_ENGAGEMENT',
         14 : 'LOCAL_CAMPAIGN',
         15 : 'SHOPPING_COMPARISON_LISTING_ADS',
         16 : 'SMART_CAMPAIGN',
         17 : 'VIDEO_SEQUENCE',
         18 : 'APP_CAMPAIGN_FOR_PRE_REGISTRATION'},
    'advertising_channel_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'SEARCH',
         3 : 'DISPLAY',
         4 : 'SHOPPING',
         5 : 'HOTEL',
         6 : 'VIDEO',
         7 : 'MULTI_CHANNEL',
         8 : 'LOCAL',
         9 : 'SMART',
         10 : 'PERFORMANCE_MAX',
         11 : 'LOCAL_SERVICES',
         12 : 'DISCOVERY'},
    'bidding_strategy_goal_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'OPTIMIZE_INSTALLS_TARGET_INSTALL_COST',
         3 : 'OPTIMIZE_IN_APP_CONVERSIONS_TARGET_INSTALL_COST',
         4 : 'OPTIMIZE_IN_APP_CONVERSIONS_TARGET_CONVERSION_COST',
         5 : 'OPTIMIZE_RETURN_ON_ADVERTISING_SPEND',
         6 : 'OPTIMIZE_PRE_REGISTRATION_CONVERSION_VOLUME',
         7 : 'OPTIMIZE_INSTALLS_WITHOUT_TARGET_INSTALL_COST'},
    'bidding_strategy_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'COMMISSION',
         3 : 'ENHANCED_CPC',
         4 : 'INVALID',
         5 : 'MANUAL_CPA',
         6 : 'MANUAL_CPC',
         7 : 'MANUAL_CPM',
         8 : 'MANUAL_CPV',
         9 : 'MAXIMIZE_CONVERSIONS',
         10 : 'MAXIMIZE_CONVERSION_VALUE',
         11 : 'PAGE_ONE_PROMOTED',
         12 : 'PERCENT_CPC',
         13 : 'TARGET_CPA',
         14 : 'TARGET_CPM',
         15 : 'TARGET_IMPRESSION_SHARE',
         16 : 'TARGET_OUTRANK_SHARE',
         17 : 'TARGET_ROAS',
         18 : 'TARGET_SPEND'},
    'field_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'HEADLINE',
         3 : 'DESCRIPTION',
         4 : 'MANDATORY_AD_TEXT',
         5 : 'MARKETING_IMAGE',
         6 : 'MEDIA_BUNDLE',
         7 : 'YOUTUBE_VIDEO',
         8 : 'BOOK_ON_GOOGLE',
         9 : 'LEAD_FORM',
         10 : 'PROMOTION',
         11 : 'CALLOUT',
         12 : 'STRUCTURED_SNIPPET',
         13 : 'SITELINK',
         14 : 'MOBILE_APP',
         15 : 'HOTEL_CALLOUT',
         16 : 'CALL',
         17 : 'PRICE',
         18 : 'LONG_HEADLINE',
         19 : 'BUSINESS_NAME',
         20 : 'SQUARE_MARKETING_IMAGE',
         21 : 'PORTRAIT_MARKETING_IMAGE',
         22 : 'LOGO',
         23 : 'LANDSCAPE_LOGO',
         24 : 'VIDEO',
         25 : 'CALL_TO_ACTION_SELECTION'},
    'ad_network_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'SEARCH',
         3 : 'SEARCH_PARTNERS',
         4 : 'CONTENT',
         5 : 'YOUTUBE_SEARCH',
         6 : 'YOUTUBE_WATCH',
         7 : 'MIXED'},
    'asset_type' :
         {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'YOUTUBE_VIDEO',
         3 : 'MEDIA_BUNDLE',
         4 : 'IMAGE',
         5 : 'TEXT',
         6 : 'LEAD_FORM',
         7 : 'BOOK_ON_GOOGLE',
         8 : 'PROMOTION',
         9 : 'CALLOUT',
         10 : 'STRUCTURED_SNIPPET',
         11 : 'SITELINK',
         12 : 'PAGE_FEED',
         13 : 'DYNAMIC_EDUCATION',
         14 : 'MOBILE_APP',
         15 : 'HOTEL_CALLOUT',
         16 : 'CALL',
         17 : 'PRICE',
         18 : 'CALL_TO_ACTION',
         19 : 'DYNAMIC_REAL_ESTATE',
         20 : 'DYNAMIC_CUSTOM',
         21 : 'DYNAMIC_HOTELS_AND_RENTALS',
         22 : 'DYNAMIC_FLIGHTS',
         23 : 'DISCOVERY_CAROUSEL_CARD',
         24 : 'DYNAMIC_TRAVEL',
         25 : 'DYNAMIC_LOCAL',
         26 : 'DYNAMIC_JOBS'},
    'performance_label' :
         {0 : 'UNSPECIFIED',
          1 : 'UNKNOWN',
          2 : 'PENDING',
          3 : 'LEARNING',
          4 : 'LOW',
          5 : 'GOOD',
          6 : 'BEST'},
    'ad_serving_optimization_status' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'CTR_OPTIMIZE',
         3 : 'CONVERSION_OPTIMIZE',
         4 : 'ROTATE',
         5 : 'ROTATE_INDEFINITELY',
         6 : 'UNAVAILABLE'},
    'video_brand_safety_suitability' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'EXPANDED_INVENTORY',
         3 : 'STANDARD_INVENTORY',
         4 : 'LIMITED_INVENTORY'},
    'ad_rotation_mode' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'OPTIMIZE',
         3 : 'ROTATE_FOREVER'},
    'ad_group_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'SEARCH_STANDARD',
         3 : 'DISPLAY_STANDARD',
         4 : 'SHOPPING_PRODUCT_ADS',
         5 : 'HOTEL_ADS',
         6 : 'SHOPPING_SMART_ADS',
         7 : 'VIDEO_BUMPER',
         8 : 'VIDEO_TRUE_VIEW_IN_STREAM',
         9 : 'VIDEO_TRUE_VIEW_IN_DISPLAY',
         10 : 'VIDEO_NON_SKIPPABLE_IN_STREAM',
         11 : 'VIDEO_OUTSTREAM',
         12 : 'SEARCH_DYNAMIC_ADS',
         13 : 'SHPPING_COMPARISON_LISTING_ADS',
         14 : 'PROMOTED_HOTEL_ADS',
         15 : 'VIDEO_RESPONSIVE',
         16 : 'VIDEO_EFFICIENT_REACH',
         17 : 'SMART_CAMPAIGN_ADS'},
    'ad_type' :
        {0 : 'UNSPECIFIED',
         1 : 'UNKNOWN',
         2 : 'TEXT_AD',
         3 : 'EXPANDED_TEXT_AD',
         4 : 'EXPANDED_DYNAMIC_SEARCH_AD',
         5 : 'HOTEL_AD',
         6 : 'SHOPPING_SMART_AD',
         7 : 'SHOPPING_PRODUCT_AD',
         8 : 'VIDEO_AD',
         9 : 'IMAGE_AD',
         10 : 'RESPONSIVE_SEARCH_AD',
         11 : 'LEGACY_RESPONSIVE_DISPLAY_AD',
         12 : 'APP_AD',
         13 : 'LEGACY_APP_INSTALL_AD',
         14 : 'RESPONSIVE_DISPLAY_AD',
         15 : 'LOCAL_AD',
         16 : 'HTML_5_UPLOAD_AD',
         17 : 'DYNAMIC_HTML_5_AD',
         18 : 'APP_ENGAGEMENT_AD',
         19 : 'SHOPPING_COMPARISON_LISTING_AD',
         20 : 'VIDEO_BUMPER_AD',
         21 : 'VIDEO_UNSKIPPABLE_IN_STREAM_AD',
         22 : 'VIDEO_OUTSTREAM_AD',
         23 : 'VIDEO_TRUEVIEW_IN_STREAM_AD',
         24 : 'VIDEO_RESPONSIVE_AD',
         25 : 'SMART_CAMPAIGN_AD',
         26 : 'CALL_AD',
         27 : 'APP_PRE_REGISTRATION_AD',
         28 : 'IN_FEED_VIDEO_AD',
         29 : 'DISCOVERY_MULTI_ASSET_AD',
         30 : 'DISCOVERY_CAROUSEL_AD'}
}

ad_group_report_columns = ['customer.descriptive_name', 'campaign.name', 'campaign.id',
       'ad_group.name', 'ad_group.id', 'ad_group_ad.ad.id', 'ad_group_ad.ad.name',
       'ad_group_ad.ad.type',  'metrics.video_views',
       'metrics.conversions',
       'metrics.cost_micros',
       'metrics.active_view_measurable_impressions',
       'metrics.conversions_value', 'metrics.clicks',
       'metrics.impressions',
       'metrics.percent_new_visitors', 'metrics.active_view_impressions',
       'collected_at', 'owner_id', 'year', 'month', 'day']
campaign_index_columns = ['campaign.id', 'campaign.ad_serving_optimization_status', 'campaign.advertising_channel_sub_type',
 'campaign.advertising_channel_type','campaign.app_campaign_setting.bidding_strategy_goal_type',
 'campaign.bidding_strategy_type',  'campaign.manual_cpc.enhanced_cpc_enabled',   'campaign.optimization_score',
                          'campaign.video_brand_safety_suitability',  'year', 'month', 'day']
group_index_columns = ['ad_group.id', 'ad_group.ad_rotation_mode', 'ad_group.explorer_auto_optimizer_setting.opt_in', 'ad_group.type', 'year', 'month', 'day']


enum_dict = {
    'campaign.advertising_channel_type' : 'advertising_channel_type',
    'campaign.advertising_channel_sub_type' : 'advertising_channel_sub_type',
    'asset.type' : 'asset_type',
    'ad_group_ad_asset_view.field_type' : 'field_type',
    'ad_group_ad_asset_view.performance_label' : 'performance_label',
    'segments.ad_network_type' : 'ad_network_type'
}

enum_dict_ad_group = {
    'ad_group_ad.ad.type' : 'ad_type',
    'campaign.ad_serving_optimization_status' : 'ad_serving_optimization_status',
    'campaign.advertising_channel_sub_type' : 'advertising_channel_sub_type',
    'campaign.advertising_channel_type' : 'advertising_channel_type',
    'campaign.app_campaign_setting.bidding_strategy_goal_type' : 'bidding_strategy_goal_type',
    'campaign.bidding_strategy_type' : 'bidding_strategy_type',
    'campaign.video_brand_safety_suitability' : 'video_brand_safety_suitability',
    'ad_group.ad_rotation_mode' : 'ad_rotation_mode',
    'ad_group.type' : 'ad_group_type'
}
